## README ##

# if using git, for security pswd_local/ must be added to .gitignore; 
# only the hashed file of passwords generated by this script should be copied to any public locations/github

# an additional security measure is to scp the file of hashed passwords direct to the server, rather than via github. 

rm(list=ls()); gc()

library(shinyauthr)

library(tidyverse)

library(sodium) 

#NB on linux, sodium requires manual installation of libsodium; 
# cf notes/install_libsodium_for_shinyauthr.sh 


# set uid & pwd ------------------------------------------------

user_ids <- c('u','user')


# NB this command currently sets the same pwd for all users; albeit creating different hashes

user_base_hash <- tibble::tibble(
  user = user_ids,
  password = sapply(rep('p', length(user_ids)) , sodium::password_store)
  #permissions = c("admin", "standard"),
  #name = c("User One", "User Two")
)


# save hashed file ---------------------------------------------------------------

saveRDS(  user_base_hash, 'pswd/pwd_hash_tbl.Rds')

# next steps --------------------------------------------------------------

#scp hashed .Rds to server 
